<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__swal2-success-ring</name>
   <tag></tag>
   <elementGuidId>1384fe91-21ed-44fe-a5f8-86ffa06986e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.swal2-success-ring</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2eb9c6cd-e8dc-44d3-8633-89af65377795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-success-ring</value>
      <webElementGuid>8df79bfe-2eb1-4e90-a2ef-88485dfee09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;swal2-shown swal2-height-auto&quot;]/body[@class=&quot;swal2-shown swal2-height-auto&quot;]/div[@class=&quot;swal2-container swal2-center swal2-backdrop-show&quot;]/div[@class=&quot;swal2-popup swal2-modal swal2-icon-success swal2-show&quot;]/div[@class=&quot;swal2-icon swal2-success swal2-icon-show&quot;]/div[@class=&quot;swal2-success-ring&quot;]</value>
      <webElementGuid>b728b6c8-a6ec-4b28-ba41-6137d9d25716</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>0659f8db-7fbd-40af-acc8-a2d9e9f785bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
