<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Confirm your code and conclude the transaction</name>
   <tag></tag>
   <elementGuidId>0a45eeed-ce63-4507-b33e-a0b99ef09d33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.code-modal__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ee89bc1d-43c8-4a78-95cb-fc3776625292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>code-modal__title</value>
      <webElementGuid>f0ba886e-2dee-43d8-a0d7-74b21109b4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm your code and conclude the transaction</value>
      <webElementGuid>5271fd4e-5f4c-4ce4-8333-a943df2dabd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-wrapper&quot;]/div[@class=&quot;modal__inner&quot;]/h1[@class=&quot;code-modal__title&quot;]</value>
      <webElementGuid>5291d38e-d108-423b-8ca6-c2f4bc220a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/h1</value>
      <webElementGuid>33394718-ed5a-45f8-8a47-6ef2b82ce770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register and start transferring'])[1]/preceding::h1[1]</value>
      <webElementGuid>de8f11b5-d613-48f8-a636-d9f4d03d7c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm your code and conclude the transaction']/parent::*</value>
      <webElementGuid>74ca933e-293f-4ed2-b6df-522cb0cfdeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>4bf1d409-a903-466a-9f0e-1bef7854b363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Confirm your code and conclude the transaction' or . = 'Confirm your code and conclude the transaction')]</value>
      <webElementGuid>87f7f0f5-f8fe-4d7c-b085-6a8170a4dbec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
