<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm your code and conclude the tr_440cde</name>
   <tag></tag>
   <elementGuidId>4b56b284-9d9c-499d-88dd-6d5dbae36cf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fc3727a-9980-474f-a7aa-193b043f2f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f43d0bc-c8ca-4e60-abed-59a84d6868f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code2</value>
      <webElementGuid>52b24ca2-3b1a-47bf-aa75-dfdb97100cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1a138959-9ccb-40b2-a7ae-506e75c7f448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input2</value>
      <webElementGuid>a49b12b4-810a-49ad-aa2c-20712f866f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8d965f09-7015-4033-b67b-87ebdead458c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>squared-input__rounded</value>
      <webElementGuid>fc11feb8-88aa-4dcd-8e5d-4b34297409ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input2&quot;)</value>
      <webElementGuid>d65216b6-b772-4223-82a4-d60c8cccf5bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input2']</value>
      <webElementGuid>e927034e-3d4e-4090-99e0-47848e43b3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/form/div/input[2]</value>
      <webElementGuid>22fd6b0f-1b46-4322-985f-35a828c7fcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>66ceb6ed-0a85-45d3-ae21-b60719d26adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code2' and @placeholder = '1' and @id = 'input2']</value>
      <webElementGuid>9450f5b1-7dae-43e0-9248-0af47453ff32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
