<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm your code and conclude the tr_006784</name>
   <tag></tag>
   <elementGuidId>a01fddf7-c8d3-4556-8a5f-34b316f677ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b42f562-f36e-4659-9d48-94a5c3713e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a148ef0-dfe6-4114-ae15-38fb4733f3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code3</value>
      <webElementGuid>1027e00e-9380-4407-a90c-ce1e6d98997c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5086d2ce-9386-4e23-bbba-59b038f2f173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input3</value>
      <webElementGuid>2aa636da-0e33-4403-a91d-49f9dd706e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b0aa8dd2-60f7-4d0f-826c-a68d84b4b1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>squared-input__rounded</value>
      <webElementGuid>f2997d50-7f06-41d1-a124-7353ef00a16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input3&quot;)</value>
      <webElementGuid>80a4e0b0-5d07-4fc8-803a-9534fc04a8a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input3']</value>
      <webElementGuid>e2084b27-cfd5-47cc-8a69-9930af128295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/form/div/input[3]</value>
      <webElementGuid>662c05e9-2402-45df-b394-7cbadef86945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>cac7aa4f-0c0b-421c-97b7-b5820e920609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code3' and @placeholder = '1' and @id = 'input3']</value>
      <webElementGuid>26964b80-166a-48a7-8b43-274139160c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
