<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm your code and conclude the tr_006784</name>
   <tag></tag>
   <elementGuidId>35d9286e-df1d-4923-a7c2-5ae5f3a5bee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed821a14-35a3-40d4-bb5f-054e6da7d439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fab29ac-5122-4ba0-97d7-efb83937ad1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code3</value>
      <webElementGuid>94165758-58ea-47ab-9374-e1d7ed1b0bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>652855fc-180a-4542-bd95-7323b528581f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input3</value>
      <webElementGuid>29a95991-755f-47e3-b400-aa9113b3cd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1e0409ec-e464-46b2-ae82-e581729c2d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>squared-input__rounded</value>
      <webElementGuid>926bb4f2-ee61-4023-bb92-5102a9a7aa50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input3&quot;)</value>
      <webElementGuid>27fef23a-e4c0-426b-9a59-46a0300593fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input3']</value>
      <webElementGuid>a4cdbe18-e764-400a-9281-8be418010712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/form/div/input[3]</value>
      <webElementGuid>794f4f27-1a43-410d-8dd9-1687412fd91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>11d1e8e9-59c4-4b7a-93cd-28937ed43a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code3' and @placeholder = '1' and @id = 'input3']</value>
      <webElementGuid>113a7c72-2512-4fc7-8c12-8f5b74d7282b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
