<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elem_5</name>
   <tag></tag>
   <elementGuidId>06175fb5-8d9b-4826-a7f4-b00a68710c4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.t-align-right.font-bold.primary-font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[5]/div[3]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c12e5b3e-e6fe-4c88-aa72-e0c658d3f254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-align-right font-bold primary-font</value>
      <webElementGuid>561a11eb-96ad-4179-a09e-ef4ccf9d7018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> +5€</value>
      <webElementGuid>a3bc1b10-ea83-4ba6-be39-4e1bdca7da4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-container__container&quot;]/div[@class=&quot;main-container__container-inner&quot;]/div[@class=&quot;container__direction-column-start&quot;]/div[@class=&quot;single-contact__container&quot;]/div[@class=&quot;single-contact__info&quot;]/div[@class=&quot;single-contact__phone&quot;]/p[@class=&quot;t-align-right font-bold primary-font&quot;]</value>
      <webElementGuid>1b310682-9d28-4579-bf17-00eef63717f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[5]/div[3]/div/p</value>
      <webElementGuid>e6ca7854-52a4-4804-b6ec-53f5bb81858d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all'])[1]/following::p[2]</value>
      <webElementGuid>4b0beda0-1b3a-441c-86f7-c94a5bad1cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piggy Transactions'])[1]/following::p[2]</value>
      <webElementGuid>fcc3843b-5855-428c-8de4-d641f4e8710f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::p[3]</value>
      <webElementGuid>bc0d54ba-8ea9-44ed-9df5-ad0654570a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5€']/parent::*</value>
      <webElementGuid>29efa17a-193d-4d2e-a5a6-692ecff94016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>e2d2f42d-c6bd-455d-a74f-5b9ada3269d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' +5€' or . = ' +5€')]</value>
      <webElementGuid>d5d890c1-709f-4387-9509-0c178dd0a913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
