<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elem_Confirm your code and conclude the transaction</name>
   <tag></tag>
   <elementGuidId>509831fe-1856-4d67-bdb4-fc97260f26af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.code-modal__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5cbec93c-1e72-493c-b7fc-198f7fe6aae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>code-modal__title</value>
      <webElementGuid>1b2d5ee0-e74b-4524-8e3d-608e4333fa6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm your code and conclude the transaction</value>
      <webElementGuid>e74baf45-b405-4713-84a6-78b1151ce3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-wrapper&quot;]/div[@class=&quot;modal__inner&quot;]/h1[@class=&quot;code-modal__title&quot;]</value>
      <webElementGuid>250356f6-f838-4d5e-ba78-9733d3a0fb5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/h1</value>
      <webElementGuid>72866712-086e-4585-b417-ff64e43711c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register and start transferring'])[1]/preceding::h1[1]</value>
      <webElementGuid>455dc038-60ed-418a-8ff4-8585cf35bf77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm your code and conclude the transaction']/parent::*</value>
      <webElementGuid>ea931969-0727-4470-a636-ae49f09be0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>fd867e4c-0e2f-4ded-b51d-0df5e49ab61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Confirm your code and conclude the transaction' or . = 'Confirm your code and conclude the transaction')]</value>
      <webElementGuid>70d72693-78d0-486b-b9f1-bba1c12a7aae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
