<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elem_Piggy Bank</name>
   <tag></tag>
   <elementGuidId>f4a0b60a-7ddd-43a2-b481-7339137415ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.contact__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>743218a8-3523-413d-b46b-75920b31fb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contact__title</value>
      <webElementGuid>dac83e51-3f36-469c-90ff-42c65d932548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Piggy Bank</value>
      <webElementGuid>f1f76103-9574-46c7-b8f8-11f2a3376838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-container__container&quot;]/div[@class=&quot;main-container__container-inner&quot;]/div[@class=&quot;container__direction-column-start&quot;]/div[@class=&quot;contact__header__wrapper mt-50&quot;]/h1[@class=&quot;contact__title&quot;]</value>
      <webElementGuid>b09bc260-000e-48a2-b3b2-8679b947f8ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/h1</value>
      <webElementGuid>983f06b5-16b4-49f7-94a2-94f50c230bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>f0cc74c5-69d8-470e-8ca7-78b40c24d31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Piggy Bank' or . = 'Piggy Bank')]</value>
      <webElementGuid>a793733b-d2b2-4556-8191-e0d863e7d7ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
