<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elem_Seems like you dont have any moviments in your account</name>
   <tag></tag>
   <elementGuidId>0558477d-8291-4734-aaca-31540e8e8533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.t-align-center.primary-font.mt-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>05d1bfad-5a71-4e7a-b72b-edab9ab951a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-align-center primary-font mt-30</value>
      <webElementGuid>241b275a-2d31-4e93-a391-71ec4a9a2c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seems like you don't have any moviments in your account</value>
      <webElementGuid>60f795b2-e19b-4f66-a20c-4de959b52a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-container__container&quot;]/div[@class=&quot;main-container__container-inner&quot;]/div[1]/h1[@class=&quot;t-align-center primary-font mt-30&quot;]</value>
      <webElementGuid>daf37599-da24-4a79-bd4b-ea896c27400b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/h1</value>
      <webElementGuid>17c2d81c-0f78-4451-9163-bf944dc4c8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/following::h1[1]</value>
      <webElementGuid>6bd84f58-d87d-48f7-b475-4aa427fa743a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::h1[1]</value>
      <webElementGuid>56e16360-160a-4192-b493-f393ef84373c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transacations'])[1]/preceding::h1[1]</value>
      <webElementGuid>61965e9e-4381-43f9-b433-e69e7713bf65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div/div/h1</value>
      <webElementGuid>60f68614-890f-4882-876b-c108429986c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = concat(&quot;Seems like you don&quot; , &quot;'&quot; , &quot;t have any moviments in your account&quot;) or . = concat(&quot;Seems like you don&quot; , &quot;'&quot; , &quot;t have any moviments in your account&quot;))]</value>
      <webElementGuid>541d2e15-5917-42f9-a036-b534d7b8d98b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
