<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elem_Seems like you dont have any contacts</name>
   <tag></tag>
   <elementGuidId>783cba4d-f844-499c-be47-2318a6b5f236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.t-align-center.primary-font.mt-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>efbb3a05-5a3d-42c0-b75c-351bbe3044cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-align-center primary-font mt-30</value>
      <webElementGuid>58907efe-9f76-4099-ad4f-b5349f230d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seems like you don't have any contacts</value>
      <webElementGuid>5cd053ab-b09c-4206-a66a-571b18c43def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-container__container&quot;]/div[@class=&quot;main-container__container-inner&quot;]/div[1]/h1[@class=&quot;t-align-center primary-font mt-30&quot;]</value>
      <webElementGuid>558aeae7-aaa2-4da0-8971-e196c9456ef4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/h1</value>
      <webElementGuid>00c6ea98-5615-4c6d-b253-afaf6e80ceb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/following::h1[1]</value>
      <webElementGuid>664f83de-a8d6-4274-a559-e905eaf632f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::h1[1]</value>
      <webElementGuid>15165ed6-0230-4dea-9fa4-c736d0441892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transacations'])[1]/preceding::h1[1]</value>
      <webElementGuid>a342025f-533e-432f-8da2-401ce16fd00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div/div/h1</value>
      <webElementGuid>55e78146-7aa5-4c55-b194-df750f4c5ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = concat(&quot;Seems like you don&quot; , &quot;'&quot; , &quot;t have any contacts&quot;) or . = concat(&quot;Seems like you don&quot; , &quot;'&quot; , &quot;t have any contacts&quot;))]</value>
      <webElementGuid>2d061ab0-12fb-4a51-8ac9-8249d1a16c5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
