<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elem_This contact is not a V-Card user yet</name>
   <tag></tag>
   <elementGuidId>c5819333-9b36-43a3-8899-d744237031aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swal2-html-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swal2-html-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f6bb173-1b4f-4754-8285-83748b2b9c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-html-container</value>
      <webElementGuid>bed20054-8753-4c74-b61b-3d3370392508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-html-container</value>
      <webElementGuid>a064ca63-af97-465c-8734-245582853968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This contact is not a V-Card user yet</value>
      <webElementGuid>0471be46-4d49-44db-b744-467aac227329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-html-container&quot;)</value>
      <webElementGuid>47b8e914-6811-42bd-ab8c-1d3923784f0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='swal2-html-container']</value>
      <webElementGuid>213a507e-8ea0-4775-aac7-ba0878014428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::div[1]</value>
      <webElementGuid>a371b423-1846-4485-b460-8b0b6d07d3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[2]</value>
      <webElementGuid>d7ff73f6-623c-4560-9ddc-f7cd4a4291f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[5]</value>
      <webElementGuid>6111c794-7232-4649-84ee-59e5f1334cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::div[5]</value>
      <webElementGuid>496c1d6c-fe62-4edd-a8ae-d9c121a72f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div[2]/div/div[2]</value>
      <webElementGuid>4137dbc8-00b5-4086-969b-940b4d163858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'swal2-html-container' and (text() = 'This contact is not a V-Card user yet' or . = 'This contact is not a V-Card user yet')]</value>
      <webElementGuid>d192c384-2de2-47c5-8246-1f52d8699fbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
