<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Incomes end date</name>
   <tag></tag>
   <elementGuidId>8293dcfb-2ac8-4a09-9272-88fd36746546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;end-date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='end-date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b32ba39-2be3-4836-b29c-48c010befa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>08aeee5b-3e8d-43d9-a850-af0f3d6c22cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transactions__filter</value>
      <webElementGuid>2ead7921-b3b8-4ef8-aed1-0cac3685735e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end-date</value>
      <webElementGuid>ab45167e-983b-4c6a-9672-38ed0848e148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>End Date</value>
      <webElementGuid>f50b7ae8-5f89-42b1-9b52-1ac67322429b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-container__container&quot;]/div[@class=&quot;main-container__container-inner&quot;]/div[@class=&quot;container__direction-column-start&quot;]/div[@class=&quot;input__group-col&quot;]/div[@class=&quot;transationcs__filters&quot;]/input[@class=&quot;transactions__filter&quot;]</value>
      <webElementGuid>7bb50b07-48ff-4132-bbb9-31d71e803a75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='end-date']</value>
      <webElementGuid>807d91ba-ea6b-4e25-918e-0e802976f8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div[5]/input[2]</value>
      <webElementGuid>69aa1b5a-0e14-4ee1-8a3e-8428e1690226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>81b41a5c-0cc2-4ad8-8660-e9626b04cb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'end-date' and @placeholder = 'End Date']</value>
      <webElementGuid>bbbdc613-9826-4246-b8fe-6adebc31b235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
