<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_New contactNamePhoneAdd contact</name>
   <tag></tag>
   <elementGuidId>b5ec2ca2-d5a9-4d48-87af-572bbeb5d3c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>5ebf9fec-09f5-466d-ac06-8170dcfaa4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New contactNamePhoneAdd contact </value>
      <webElementGuid>41913b1a-e030-404f-9b7b-d1411abb2b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/form[1]</value>
      <webElementGuid>fe16493f-090d-4e44-92cd-ae8168aec2de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/form</value>
      <webElementGuid>b486854b-31e5-41e8-ba39-e1f1c5c5503e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>83c84ee0-eede-448a-a916-eadb06ee1152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'New contactNamePhoneAdd contact ' or . = 'New contactNamePhoneAdd contact ')]</value>
      <webElementGuid>9bf09547-b0ef-481b-8473-0f7f8686f0f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
