<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Invalid Portuguese phone number</name>
   <tag></tag>
   <elementGuidId>75f6a08e-9e10-4c76-b23c-9e5f6712a8d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/form/div/div/div/div[2]/div/div[2]/span[2]/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>541c658f-5309-499e-8a44-241c5445d919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Portuguese phone number</value>
      <webElementGuid>09acb2bc-b20d-4930-9ac5-e53518a9d37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/form[1]/div[@class=&quot;main-container__container&quot;]/div[@class=&quot;main-container__container-inner&quot;]/div[@class=&quot;container__direction-column&quot;]/div[@class=&quot;contact__form-wrapper&quot;]/div[@class=&quot;contact__inputs-wrapper&quot;]/div[@class=&quot;input__group-col&quot;]/span[@class=&quot;input__error-text&quot;]/ul[1]/li[1]</value>
      <webElementGuid>edb66869-bb86-4572-8922-db8ea13320cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/form/div/div/div/div[2]/div/div[2]/span[2]/ul/li</value>
      <webElementGuid>09042959-4732-4b63-a3aa-3a6c86ee461e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::li[1]</value>
      <webElementGuid>1f00653f-70ec-4495-a949-9464d2fedf3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::li[1]</value>
      <webElementGuid>5c683c4e-7a95-424a-88ed-a2a68e361e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Portuguese phone number']/parent::*</value>
      <webElementGuid>b7b95c28-9aad-4879-b85f-9ee836aa0519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>2406d513-9114-4b40-924f-1d714a35ccff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Invalid Portuguese phone number' or . = 'Invalid Portuguese phone number')]</value>
      <webElementGuid>25f071ec-a6a5-4745-91ae-d8d2374fb81c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
