<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Deposit Money</name>
   <tag></tag>
   <elementGuidId>f1da0c75-94a1-4f96-b453-84072e0d686b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.secondary-button.color-black.mt-30.piggy-bank__button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[3]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1584cc54-e3fe-4d60-9208-6898a43801d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/send-money/D</value>
      <webElementGuid>26990666-2ad4-495f-820c-f7fd48e0593f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondary-button color-black mt-30 piggy-bank__button</value>
      <webElementGuid>b6d34f68-7ec4-4daa-9265-77195a78da3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Deposit Money </value>
      <webElementGuid>59050849-cf40-41a8-8821-af12f41ffbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-container__container&quot;]/div[@class=&quot;main-container__container-inner&quot;]/div[@class=&quot;container__direction-column-start&quot;]/div[@class=&quot;piggy-bank__button-wrapper&quot;]/a[@class=&quot;secondary-button color-black mt-30 piggy-bank__button&quot;]</value>
      <webElementGuid>a8a6261c-864a-4246-bf51-04b3012080a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[3]/a[2]</value>
      <webElementGuid>453dcac8-6995-4aa5-a762-669914f8f526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piggy Bank'])[1]/following::a[2]</value>
      <webElementGuid>d28cf564-cec1-432d-a71a-0543d22e6780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piggy Transactions'])[1]/preceding::a[1]</value>
      <webElementGuid>72aa4294-da2f-411d-9a53-38325ab31469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all'])[1]/preceding::a[1]</value>
      <webElementGuid>7a15cbcb-6b61-46a7-924a-6b1877f7fe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deposit Money']/parent::*</value>
      <webElementGuid>cb737b8d-57df-495e-ac84-c8ec42e96f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/send-money/D')]</value>
      <webElementGuid>a16f1fcf-f3dd-4dd2-b0a6-9bad9b100100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>4a40774c-660e-4771-96c3-b47955471bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/send-money/D' and (text() = ' Deposit Money ' or . = ' Deposit Money ')]</value>
      <webElementGuid>60549c54-a209-4581-9cdd-9e8bac8a695f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
