<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create V-Card</name>
   <tag></tag>
   <elementGuidId>0ff7ad36-1737-4c7f-8c04-ca04dd3334d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.main-button--disabled.primary-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e538a7f-a882-486e-9153-b7461cb264ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-button--disabled primary-button</value>
      <webElementGuid>77f55ed1-8c3b-4262-8c8a-a4d605679c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create V-Card </value>
      <webElementGuid>1fb10936-b49a-464e-8cce-25dd0696f98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-container__container&quot;]/div[@class=&quot;main-container__container-inner&quot;]/div[@class=&quot;container__direction-column&quot;]/div[@class=&quot;register__form-wrapper&quot;]/div[@class=&quot;register__buttons-wrapper&quot;]/button[@class=&quot;main-button--disabled primary-button&quot;]</value>
      <webElementGuid>cd9c6d1a-a725-4a2e-aae2-98407ec31bf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='']</value>
      <webElementGuid>50601ba1-9bed-4aaa-90c1-239ed86fcbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div[2]/button</value>
      <webElementGuid>b535b842-960d-4c5f-8980-689a32794983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password must contain at least one special character'])[1]/following::button[1]</value>
      <webElementGuid>f7df8fa9-3e56-438c-9092-c688bfc8cad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password must contain at least one number'])[1]/following::button[1]</value>
      <webElementGuid>26f8f8a5-a5e6-406d-b06b-5d98d3518b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>8b5ea435-2382-48d5-b3af-5cd917ff8f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create V-Card']/parent::*</value>
      <webElementGuid>315c66c3-3b89-4a12-ac87-dd8d3c638b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4cb7690f-fbd0-4918-a5a7-369a8263c466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Create V-Card ' or . = 'Create V-Card ')]</value>
      <webElementGuid>b4e028c2-62ce-4944-9284-25f8c2b2f4a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
