<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_New contact</name>
   <tag></tag>
   <elementGuidId>57d7c0b6-c6f1-4a33-930e-8f8be67be53e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.contact__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/form/div/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1417a822-f08f-48e2-9cef-ecfee630df51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contact__title</value>
      <webElementGuid>c362881a-f26f-4cdc-b8a7-b16808b63388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New contact</value>
      <webElementGuid>2b445929-1a88-4613-b7af-d2911d2c8c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/form[1]/div[@class=&quot;main-container__container&quot;]/div[@class=&quot;main-container__container-inner&quot;]/div[@class=&quot;container__direction-column&quot;]/div[@class=&quot;contact__header__wrapper&quot;]/h1[@class=&quot;contact__title&quot;]</value>
      <webElementGuid>a4b0639c-dc0f-4f1c-b450-5365cfdb7d80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/form/div/div/div/div/h1</value>
      <webElementGuid>c3d0dab5-e4ac-46e7-a424-36a79f7e0b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::h1[1]</value>
      <webElementGuid>74d0b761-ef4c-40d6-8962-5b9a232a5084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/preceding::h1[1]</value>
      <webElementGuid>019a5be9-8d15-4593-9007-bc96ebdf01bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New contact']/parent::*</value>
      <webElementGuid>b7c72399-4c94-49a6-9d1c-044a34d39aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>83772e95-b9b0-4569-85ff-5d73454e16d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'New contact' or . = 'New contact')]</value>
      <webElementGuid>303e587d-22cb-4dec-962f-ed676e8c723d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
