<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm your code and conclude the tr_440cde</name>
   <tag></tag>
   <elementGuidId>ed230b6f-f341-4309-8981-4da411da2dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edf7765b-2ff8-4c4f-a5c0-e76c80e90e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dea4c494-8f82-49be-a10e-5e9ab7c6d578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code2</value>
      <webElementGuid>36315d3e-3909-448e-abf2-de6c63ae01ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1f7940a2-cf66-4b73-ac78-73ff60f56d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input2</value>
      <webElementGuid>a7b51581-08e5-4e06-bc64-c8a29d0cb412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8e28149c-4a13-450e-bf32-3931a4972185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>squared-input__rounded</value>
      <webElementGuid>59f5f413-669f-4d26-b25d-9826292b0d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input2&quot;)</value>
      <webElementGuid>947c3f4b-0cae-4057-b453-c55fc903dbad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input2']</value>
      <webElementGuid>299ac84a-e902-4170-97ed-89664a638d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/form/div/input[2]</value>
      <webElementGuid>6c012211-891f-4400-82fd-8104b0407a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>ea1781de-d267-4a96-9154-570aadfc5e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code2' and @placeholder = '1' and @id = 'input2']</value>
      <webElementGuid>05764146-2257-4ebc-9bdc-5045b763eaa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
