<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm your code and conclude the transaction_code2_ConfirmationModal</name>
   <tag></tag>
   <elementGuidId>7bd7fcf6-5e10-4f97-b548-9458a0b1e849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a555cf4-fbce-420c-952a-77203c5b71d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41085122-1bd3-4bf9-93ef-0d1d12d66ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code2</value>
      <webElementGuid>08e7909e-30e1-4a25-aed9-f4960b2ef158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>71512ae3-48ce-41c0-ba57-ffe09c38fa14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input2</value>
      <webElementGuid>fb676c40-5f14-4649-92e3-e3d93da6dfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8f54c74c-4c3a-467f-8b9b-ac3b1c7fde72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>squared-input__rounded</value>
      <webElementGuid>ccbdc88d-5d2c-47b7-950c-d50dab4cf2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input2&quot;)</value>
      <webElementGuid>fb9d54d2-6915-431a-8a41-1d882c99189e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input2']</value>
      <webElementGuid>6f9797f9-0fb5-472d-9325-4be8e7f53ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/form/div/input[2]</value>
      <webElementGuid>90e893e7-5aee-4c25-bb6b-8fe12723bfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>49a41b0a-4f88-4a1b-b4b8-92fc3d740994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code2' and @placeholder = '1' and @id = 'input2']</value>
      <webElementGuid>b7ea1869-f633-47d0-beca-6c90b52c5a10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
